name: app_thuengmue
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  uuid: ^3.0.7
  molten_navigationbar_flutter: ^1.0.0
  font_awesome_flutter: ^10.3.0
  google_fonts: ^5.1.0
  flutter_svg : ^0.22.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/